name: fe-test buildah
on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build-buildah.yml
    with:
      image_name: fe-test-buildah
      path: dockerfiles/fe-test
      push_to_ghcr: true
      labels: |
        "org.opencontainers.image.title": "Fedora Test"
         "org.opencontainers.image.description": "Hello world"
      #extra_platforms: linux/arm64