name: Reusable Build and Push
on:
  workflow_call:
    inputs:
      image_name:
        description: "The name of the container image."
        required: true
        type: string
      path:
        description: "The path of the Docker file, eg. dockerfiles/fe-test"
        required: true
        type: string
      extra_platforms:
        description: Extra platforms, eg. linux/arm64
        required: false
        type: string
        default: ""
      push_to_ghcr:
        description: "Push to ghcr.io"
        required: false
        type: boolean
        default: false
      max_space:
        description: "Maximize build space"
        required: false
        type: boolean
        default: false
      extra_tags:
        description: |
          "Extra Tags, ONE TAG ONE LINE, ex:
            type=raw,value=test
            type=raw,value=py311
            type=raw,value=py311-{{date 'YYYYMMDD'}}
          "
        required: false
        type: string
        default: ""
      labels:
        description: |
          "Optional labels for the Docker image.
          eg.
          org.opencontainers.image.description=Another description (Actually nothing happened)
          "
        required: false
        type: string
        default: ""
      annotations:
        description: |
          "Optional annotations for the Docker image.
          eg.
          org.opencontainers.image.description=Another description (Also nothing happened)
          "
        required: false
        type: string
        default: ""

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Maximize build space
        if: ${{ inputs.max_space == true }}
        uses: ublue-os/remove-unwanted-software@v7
      
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0
      
      - name: Set up QEMU
        if: ${{ inputs.extra_platforms != '' }}
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}
          flavor: |
            latest=true
          tags: |
             type=raw,value={{date 'YYYYMMDD'}}
             ${{ inputs.extra_tags }}
          labels: |
            ${{ inputs.labels }}
          annotations: ${{ inputs.annotations }}
      
      - name: Log in to GitHub Container Registry
        if: ${{ inputs.push_to_ghcr == true }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to ghcr.io
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.path }}
          push: ${{ inputs.push_to_ghcr }}
          #cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:buildcache
          #cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:buildcache,mode=max,compression=zstd
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,${{ inputs.extra_platforms }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
